import 'package:training_request/utils/const/app_img.dart';


class HomeDummy {
  List<Map<String, dynamic>> homeData = [
    {
      'studentLat': 37.7749,
      'studentLong': -122.4194,
      'studentLocation': 'San Francisco, CA',
      'studentStateCountry': 'California, USA',
      'driverLat': 37.8044,
      'driverLong': -122.2711,
      'driverLocation': 'Oakland, CA',
      'driverStateCountry': 'California, USA',
      'studentRating': 4.8,
      'studentProfilePic': 'https://example.com/pic1.jpg',
      'studentName': 'John Doe',
      'requestHours': '2',
      'price': 40.0,
      'bookingId': 'BK001',
      'status': 'pending',
    },
    {
      'studentLat': 34.0522,
      'studentLong': -118.2437,
      'studentLocation': 'Los Angeles, CA',
      'studentStateCountry': 'California, USA',
      'driverLat': 34.1478,
      'driverLong': -118.1445,
      'driverLocation': 'Pasadena, CA',
      'driverStateCountry': 'California, USA',
      'studentRating': 4.5,
      'studentProfilePic': 'https://example.com/pic2.jpg',
      'studentName': 'Jane Smith',
      'requestHours': '3',
      'price': 60.0,
      'bookingId': 'BK002',
      'status': 'confirmed',
    },
    {
      'studentLat': 40.7128,
      'studentLong': -74.0060,
      'studentLocation': 'New York, NY',
      'studentStateCountry': 'New York, USA',
      'driverLat': 40.7306,
      'driverLong': -73.9352,
      'driverLocation': 'Brooklyn, NY',
      'driverStateCountry': 'New York, USA',
      'studentRating': 4.9,
      'studentProfilePic': 'https://example.com/pic3.jpg',
      'studentName': 'Alice Johnson',
      'requestHours': '1.5',
      'price': 35.0,
      'bookingId': 'BK003',
      'status': 'completed',
    },
    {
      'studentLat': 41.8781,
      'studentLong': -87.6298,
      'studentLocation': 'Chicago, IL',
      'studentStateCountry': 'Illinois, USA',
      'driverLat': 41.8500,
      'driverLong': -87.6500,
      'driverLocation': 'South Loop, IL',
      'driverStateCountry': 'Illinois, USA',
      'studentRating': 4.6,
      'studentProfilePic': 'https://example.com/pic4.jpg',
      'studentName': 'Michael Lee',
      'requestHours': '4',
      'price': 80.0,
      'bookingId': 'BK004',
      'status': 'cancelled',
    },
  ];
}

